name: mmoInfoCompass
main: mmo.Info.MMOInfoCompass
version: 1.0
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [Spout,mmoCore,mmoInfo]

description: Adds {compass} to the info tokens
permissions:
  mmo.info.compass:
    description: Allows {compass} to show the current player direction
    default: op
