name: mmoInfoCompass
version: ${releaseVersion} b${buildNumber}
description: Adds a {compass} token to the mmoInfo token list.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Info.MMOInfoCompass
depend: [Spout, mmoCore, mmoInfo]


permissions:
    mmo.info.compass:
        description: Allows {compass} to show the current player direction
        default: op
